version: '2.1'
services:
  service:
    build:
      context: .
      dockerfile: ./framework-Dockerfile
    command: bash -c "python3 -m framework.cli --silent --docker"
    ports:
      - "5001:80"
    depends_on:
      - mongodb
    networks:
      - backend
      - frontend
    volumes:
      - malwarefolder:/tmp

  website:
    build:
      context: .
      dockerfile: ./webinterface-Dockerfile
    command: bash -c "python3 start.py && /usr/local/bin/gunicorn --log-level=critical -w 1 --certfile=certs/cert.pem --keyfile=certs/key.pem -b :8000 web:app"
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
    volumes:
      - malwarefolder:/tmp
    healthcheck:
      disable: true 

  mongodb:
    build:
      context: .
      dockerfile: ./mongodb-Dockerfile
    ports:
      - '27017:27017'
    networks:
      - backend

volumes:
  malwarefolder:

networks:
  frontend:
    internal: false
  backend:
    internal: true
